(ns jepsen.sql.gen-test
  (:require [clojure [pprint :refer [pprint]]
                     [test :refer :all]]
            [clojure.test.check.generators :as g]
            [jepsen [random :as rand]]
            [jepsen.sql [ast :refer :all]
                        [gen :refer :all]]))

(deftest gen-schema-test
  (is (= (schema
           [(table "t"
                   [(column "c" text-type {:primary-key? true})
                    (column "b" boolean-type)
                    (column "a" integer-type)])
            (table "u"
                   [(column "b" integer-type {:primary-key? true})])])
         (g/generate (gen-schema {:max-table-count  3
                                  :max-column-count 3})
                     2 123))))

(deftest gen-case-test
  (rand/with-seed 0
    (let [case (generate {:max-statement-count 1024})]
      (is (= [["CREATE TABLE t (b TEXT PRIMARY KEY, a TEXT, c TEXT, d BOOLEAN)"]
              ["CREATE TABLE v (a BOOLEAN, c INTEGER PRIMARY KEY, b INTEGER, d BOOLEAN)"]
              ["CREATE TABLE u (d INTEGER)"]]
             (mapv sql (setup case))))

      (is (= [["DROP TABLE t"] ["DROP TABLE v"] ["DROP TABLE u"]]
             (mapv sql (teardown case))))
      ; You're meant to replace this when the generators change; the idea is to
      ; look through the history by hand and make sure it seems reasonable;
      ; you're getting a nice blend of statements and predicates, etc.
      ;(mapv (comp prn sql) (:statements case))
      (is (= [
["SELECT * FROM v"]
["SELECT * FROM v"]
["DELETE FROM v WHERE ?" true]
["SELECT * FROM v WHERE (((d = ?) = ?) AND (d OR (? = a)) AND ((d OR ? OR ? OR a) OR (a = c)) AND a)" false 38 nil true true]
["INSERT INTO v (a, c, b, d) VALUES (?, ?, ?, ?)" nil -12 176 false]
["DELETE FROM t"]
["SELECT * FROM v"]
["SELECT * FROM u WHERE (d = d)"]
["INSERT INTO u (d) VALUES (?)" -1]
["INSERT INTO u (d) VALUES (?)" 959823]
["UPDATE v SET a = ?, b = ?, d = ?, c = ? WHERE (? = ?)" true -3 nil 1072218635 -1495720 false]
["INSERT INTO v (a, c, b, d) VALUES (?, ?, ?, ?)" nil -300 -15583 true]
["INSERT INTO v (d, c, a, b) VALUES (?, ?, ?, ?)" true -2 nil 229]
["SELECT * FROM v WHERE ?" nil]
["UPDATE v SET a = ?" nil]
["INSERT INTO v (a, b, c, d) VALUES (?, ?, ?, ?)" true 3870 -4395 false]
["INSERT INTO v (d, c, a, b) VALUES (?, ?, ?, ?)" true 7032 true -812134460]
["UPDATE u SET d = ?" -18549318]
["DELETE FROM u WHERE ((d = d) AND (NOT ?) AND (NOT (? = d)))" nil 4416307]
["SELECT * FROM t"]
["INSERT INTO t (c, d, b, a) VALUES (?, ?, ?, ?)" " ne1aClAXIxCEeocMg-DFLpX" false "FyfSYCe8" "XwykEcTkxTGi7mTvP-Cs-ZjzQTuL4Nb _"]
["SELECT * FROM v WHERE a"]
["INSERT INTO u (d) VALUES (?)" 8]
["SELECT * FROM u"]
["UPDATE v SET a = ?, b = ? WHERE (? = ((a AND d AND a) OR (? OR d) OR (c = a) OR (d = ?)))" false -31221704 -22525 nil -571]
["INSERT INTO t (c, a, b, d) VALUES (?, ?, ?, ?)" "ig" "fAKqKtfbtCm1hzYKjSaNzB1Q_3LCrsQ" "I-PH qhp1EszQE3FH2CnMXQbq44wPXV" nil]
["UPDATE t SET b = ?, d = ? WHERE (NOT ?)" "fA7E8orQI4A0Wa" true false]
["SELECT * FROM v"]
["UPDATE v SET a = ?, b = ?, d = ? WHERE ?" false 0 true true]
["INSERT INTO v (a, c, b, d) VALUES (?, ?, ?, ?)" true -635928 0 true]
["SELECT * FROM t WHERE (? = ?)" nil true]
["SELECT * FROM t"]
["SELECT * FROM u WHERE ?" nil]
["INSERT INTO u (d) VALUES (?)" -5887]
["UPDATE t SET b = ?, a = ?, c = ?, d = ? WHERE (d = d)" "c-XRTXQlYF tS6AR81H0u4j0dcnZVHU" "ESbp" "SeHBcwRK-3hog_c wC98qMOKGUiEk" nil]
["SELECT * FROM u"]
["INSERT INTO u (d) VALUES (?)" -25]
["SELECT * FROM v WHERE (? = ?)" false 516108]
["INSERT INTO t (b, d, c, a) VALUES (?, ?, ?, ?)" "VnXhwCxqZbXJOXQeGDeG" nil "N M199CTt5jiHfACB" "UkhdPvLrgU3F_ XVBFn1SI"]
["INSERT INTO u (d) VALUES (?)" 9]
["SELECT * FROM t"]
["INSERT INTO t (b, a, d, c) VALUES (?, ?, ?, ?)" "z4Tl -DU1_1Wy" "juqE5K_YqLiaq-" true "QFQw"]
["SELECT * FROM v WHERE a"]
["UPDATE v SET c = ?" 1]
["SELECT * FROM u WHERE (NOT ((? = d) AND ? AND (d = d) AND (d = d)))" 8 true]
["INSERT INTO t (d, b, a, c) VALUES (?, ?, ?, ?)" nil "g-QFLFfvmPOSAhydBQa0q" "UP3GSf2gmS5H8zlReV-ebow7ip5e" "Xi18gKMXYnMbe-UN6WEZfx"]
["UPDATE v SET b = ? WHERE a" 139]
["INSERT INTO t (c, d, b, a) VALUES (?, ?, ?, ?)" "aCx-b P4YaAm" nil "mt0-59P RRoTp2BFrEG-HsJ7 -" "aA"]
["SELECT * FROM v WHERE ?" false]
["INSERT INTO v (b, d, a, c) VALUES (?, ?, ?, ?)" 62858 true false -1]
["UPDATE t SET c = ?, d = ? WHERE ?" "0W-" false false]
["INSERT INTO t (a, b, c, d) VALUES (?, ?, ?, ?)" "77YwkTJw7TTwfXcs2" "ppM7rHLBfwNfor6h6uxUZZhAoTUo1J7" "75nc077IVn8Y33cxerCw-" false]
["SELECT * FROM t"]
["SELECT * FROM u WHERE (? = d)" 6]
["INSERT INTO u (d) VALUES (?)" 5761598]
["UPDATE u SET d = ? WHERE ((? = d) OR (d = d) OR (d = d) OR ?)" 2155 40 true]
["UPDATE u SET d = ? WHERE ?" -10467 nil]
["SELECT * FROM t WHERE d"]
["UPDATE u SET d = ? WHERE ?" 49 false]
["UPDATE u SET d = ? WHERE ?" -21167060 nil]
["SELECT * FROM t WHERE (b = a)"]
["SELECT * FROM u WHERE ((d = d) OR ((? AND ?) OR ?))" true nil false]
["SELECT * FROM t"]
["UPDATE u SET d = ?" -91773]
["SELECT * FROM t WHERE ?" nil]
["UPDATE v SET a = ?, b = ?, c = ?, d = ? WHERE (((? = ?) AND ? AND (d = b) AND (a = ?)) OR ? OR ? OR ?)" nil 3550 -9 nil false false nil false nil nil true]
["DELETE FROM t WHERE (b = ?)" false]
["INSERT INTO u (d) VALUES (?)" -28388138]
["UPDATE t SET c = ?, b = ?, d = ?, a = ? WHERE (NOT d)" "0lfuwa8truhkDWhVBpL6JFnMvGi8-NQS" "Pj4ATSoBPdin" true "eiBcItk"]
["SELECT * FROM t WHERE d"]
["SELECT * FROM t WHERE (((? = ?) = (? OR d)) = ((? = d) OR (d AND d) OR ? OR (? = ?)))" true true nil true nil "R 2odhAL " nil]
["SELECT * FROM u"]
["SELECT * FROM t WHERE (? = ((? AND ? AND d) = c))" "vTTv4dM 0h_x-8MmsulZO2O1p" false false]
["SELECT * FROM v WHERE (? OR ((c = b) OR (? = a) OR (? OR ?) OR (d = a)) OR ? OR (? = c))" false nil true false true false]
["INSERT INTO v (a, c, b, d) VALUES (?, ?, ?, ?)" false 93196 -4 false]
["INSERT INTO u (d) VALUES (?)" 108177207]
["SELECT * FROM v WHERE (((a OR d OR d) AND (NOT a) AND (? = b) AND (NOT ?)) OR ((d = c) AND ?))" false nil false]
["SELECT * FROM u WHERE (d = ?)" -4814]
["INSERT INTO t (a, d, c, b) VALUES (?, ?, ?, ?)" "Y7AAytwuuwVOyxz8J0H ZRGGvdBfBa" nil "Zcg" "uTjbF EZQVuFaFP"]
["INSERT INTO u (d) VALUES (?)" 5198]
["UPDATE t SET a = ?, c = ? WHERE d" "V 3ZNQnw6WiQL5UNnc8UWlEh2MFr" "rNo0WfAS8ZAXza3NdNvAUgqN7w"]
["SELECT * FROM u WHERE ((NOT (d = d)) AND ?)" nil]
["INSERT INTO v (c, a, b, d) VALUES (?, ?, ?, ?)" -210892849 false 7 true]
["SELECT * FROM v WHERE ?" false]
["SELECT * FROM u WHERE ?" true]
["INSERT INTO t (b, d, c, a) VALUES (?, ?, ?, ?)" "Q0lYEUV6xjqOg" true "lKj7eTQJyo6kkhdF pSST-QF7BcjTq7x" "1E6d1tlhPldtf9uUyAPQ5FJVLz3VI4ALz"]
["INSERT INTO t (d, c, b, a) VALUES (?, ?, ?, ?)" true "tZaV5MthUu9qZJfVh6rrKiIsyNmj3Y" "QLKI _22jdf0MPAUpBUQNp- " "Ogwb63_bRRiye"]
["UPDATE t SET a = ?, d = ?, b = ?, c = ? WHERE (NOT d)" "gWSqr I3SVVwdCJnOUC2rr" nil "3sEYSRlezZ4Q-ez7FiE_tH1_gmLITJ0Gt" "jdrxVF2m59Re4n-kPkEyX0X"]
["UPDATE u SET d = ? WHERE (d = ?)" -120103855 -1]
["SELECT * FROM v"]
["SELECT * FROM u WHERE (d = ?)" -3]
["INSERT INTO v (b, d, c, a) VALUES (?, ?, ?, ?)" -22738072 nil 2426 true]
["SELECT * FROM v WHERE (b = c)"]
["SELECT * FROM t WHERE d"]
["UPDATE u SET d = ?" -38372]
["INSERT INTO v (c, a, d, b) VALUES (?, ?, ?, ?)" -8 false false -323]
["SELECT * FROM v WHERE (b = b)"]
["INSERT INTO u (d) VALUES (?)" 19527837]
["SELECT * FROM u WHERE ?" nil]
["SELECT * FROM u WHERE (? OR (d = ?) OR (? = d))" true 8932 -195244]
["INSERT INTO u (d) VALUES (?)" 46]
["SELECT * FROM u"]
["SELECT * FROM u"]
["UPDATE u SET d = ? WHERE (? = ?)" 4 -2205448 29]
["SELECT * FROM t WHERE ?" nil]
["UPDATE t SET c = ?, a = ? WHERE (((? = ?) = b) = c)" "JTvQiiAKeL PodKNX3 QTJE-YEYjvYtt" "2y0dlLHU7NB_iQi-TZuI" "joAwbfTZ7_BvGcZx" false]
["SELECT * FROM u WHERE (? = d)" -6369]
["INSERT INTO t (c, a, b, d) VALUES (?, ?, ?, ?)" "DM5X3ZiNToOUuAKEYSTrc2 1mHGhS" "cfrpNXL0_lnaG9kza8xJFhbJQuXEQlC A" "0zeOAkQOLYkQjxQGMwIn7TL7nS82D4G" nil]
["INSERT INTO v (c, a, d, b) VALUES (?, ?, ?, ?)" -524255010 false false 231846]
["SELECT * FROM t WHERE ((? AND (NOT d) AND d) = (? = ?))" false "MOSuL-D" "2Xw-Ma1r IgH"]
["INSERT INTO v (b, a, c, d) VALUES (?, ?, ?, ?)" 126194123 false 116 nil]
["UPDATE v SET b = ?, d = ?, a = ? WHERE (NOT d)" 36262938 true false]
["SELECT * FROM t WHERE ?" nil]
["SELECT * FROM u WHERE ?" nil]
["INSERT INTO v (d, c, a, b) VALUES (?, ?, ?, ?)" false -508648 nil -152]
["UPDATE u SET d = ? WHERE (? = ?)" -12959 6 0]
["SELECT * FROM t WHERE (((? AND d AND ?) = (NOT d)) AND d AND (NOT d) AND (d AND (d OR d)))" true false]
["INSERT INTO v (b, c, a, d) VALUES (?, ?, ?, ?)" -1184768135 3471 true nil]
["INSERT INTO t (c, d, b, a) VALUES (?, ?, ?, ?)" "_Z WmgfY-EAC" false "ib2zrJb" "P4fjK0dOrB_xbdZHUA"]
["INSERT INTO u (d) VALUES (?)" 1]
["SELECT * FROM v WHERE (b = ?)" 54562935]
["UPDATE t SET b = ?" "o "]
["INSERT INTO v (b, a, c, d) VALUES (?, ?, ?, ?)" 50029 nil -920534 false]
["SELECT * FROM u WHERE (? = ?)" 55650 -722934]
["SELECT * FROM u WHERE ((? = ?) OR ((NOT ?) AND (NOT ?) AND (NOT ?) AND (NOT ?)) OR ((d = ?) AND (? OR ? OR ? OR ?) AND (d = d) AND ?) OR (? = d))" -58 18884 false true true true -48881 nil false false false false 64100756]
["SELECT * FROM u WHERE (? = d)" -3161928]
["INSERT INTO t (a, d, c, b) VALUES (?, ?, ?, ?)" "khY40FCNdTsKuy_Ds_jMc0lJUbHe " false "e9FEe" "keRp9U7jXZTPYrHOo"]
["SELECT * FROM v WHERE (? AND ((a = d) = b))" false]
["UPDATE t SET c = ?, b = ?, a = ?, d = ?" "27rERS_kDdyEejAzhNScSkuxpJ9" "xghYxtz9wMmu93sz0qGiVhGd" "mLmINbNFzGfFFQ1 NkyB g5U7Y50o 2sK" false]
["UPDATE t SET c = ?, d = ? WHERE ?" "kKnBHh" false false]
["INSERT INTO v (b, d, c, a) VALUES (?, ?, ?, ?)" 849762225 true -4654276 false]
["UPDATE t SET b = ?, a = ?, d = ?, c = ? WHERE (? = (? OR (NOT d) OR (b = ?) OR (a = d)))" "OQ8Tmy89dF8DuQ5F5RWKtCc" "n_pwCrDe9iO24M-DMI9Kf-06EXVktYr" nil "ZZEI6M3ifw30bwDsxeS 8d5Jv" "ugfvUK9HjPiqEPURzSzHfSoQRT88uZTF" false "gva dvT7MK"]
["UPDATE t SET b = ?, a = ? WHERE (b = ((d = b) = (? = ?)))" "JrSOXkaW7nnO4AaRT" "prhzJBwk8" "6n-6gT_5h1_9SqokyERs4Pk53k6" "yp 4ZdMguMdlQs4Hfc7JL"]
["UPDATE v SET a = ?, d = ? WHERE (? = ?)" nil false nil 11]
["INSERT INTO v (d, a, b, c) VALUES (?, ?, ?, ?)" true true -115 70]
["INSERT INTO u (d) VALUES (?)" -874]
["INSERT INTO t (c, a, b, d) VALUES (?, ?, ?, ?)" "A3mh0-W" "aQdUbMoZqwjSGArW3uHAjGkbY" "7JvrPFoHdV40uka8gOAeD" true]
["INSERT INTO v (a, b, c, d) VALUES (?, ?, ?, ?)" false 33 -2685 nil]
["UPDATE u SET d = ? WHERE (? = d)" -5811374 -32051639]
["SELECT * FROM v WHERE ?" nil]
["SELECT * FROM v WHERE (? = d)" nil]
["INSERT INTO v (d, c, a, b) VALUES (?, ?, ?, ?)" nil -506073 true 24992]
["SELECT * FROM v"]
["INSERT INTO t (b, d, c, a) VALUES (?, ?, ?, ?)" "MghSzVV1yWpeni5XLzRj0Sp IteU" false "dBN4cNo" "Z8NMXoWQPgdMtv"]
["INSERT INTO u (d) VALUES (?)" 378]
["INSERT INTO v (a, b, c, d) VALUES (?, ?, ?, ?)" false -486627900 430 true]
["SELECT * FROM t"]
["UPDATE t SET c = ?, b = ? WHERE ((? OR (NOT d) OR (? AND ?) OR (d = a)) OR ((a = a) = (? = ?)) OR d)" "SaIHbsmmnIyy" "eJadfP jeeu86Cf4Xe" true false nil "ZvobpnmQE B" "RCZBaN32MePZC1Fnhk5n2LiRtm4Dy"]
["SELECT * FROM u WHERE (NOT ?)" false]
["SELECT * FROM u WHERE (NOT (d = d))"]
["SELECT * FROM v"]
["SELECT * FROM v WHERE (? OR ((? = ?) = (NOT a)))" true true -3871703]
["SELECT * FROM v WHERE (c = ?)" 313982]
["INSERT INTO t (b, a, d, c) VALUES (?, ?, ?, ?)" "BR009Kf0Y6TY" "5" nil "a_It1"]
["SELECT * FROM t WHERE (c = (? = a))" false]
["UPDATE u SET d = ? WHERE ?" 32714733 true]
["UPDATE u SET d = ? WHERE ?" 15 false]
["UPDATE u SET d = ? WHERE ?" -1 false]
["SELECT * FROM u"]
["INSERT INTO v (b, c, d, a) VALUES (?, ?, ?, ?)" -7 16169 false nil]
["INSERT INTO v (d, a, c, b) VALUES (?, ?, ?, ?)" nil true -678 -2898726]
["DELETE FROM u"]
["SELECT * FROM t WHERE (? AND (b = b) AND d AND ((? = ?) = (a = c)))" false true true]
["INSERT INTO t (b, d, c, a) VALUES (?, ?, ?, ?)" "5Z5oF1yQ4jCuamvd2pSzqZ" nil " o1QKVzz0AZ2h xbf" "mUPPklCcfB6tJ5xuMCG-owfx2wQP"]
["SELECT * FROM v WHERE ((? OR (? = ?)) = b)" true true nil]
["SELECT * FROM t"]
["INSERT INTO t (b, c, a, d) VALUES (?, ?, ?, ?)" "6Xfu8eHL8PeJvSX83npjJhiQ0" "zkmu3xvdWVmAase-A2tJ6GD_" "wcGub" true]
["INSERT INTO t (b, a, c, d) VALUES (?, ?, ?, ?)" "H0YdgzosksxYCxpUNjCKgYEvtJP2EGN" "wIBlZvxRX7LzLX41p4g" "E2_eD2rj11faaPQBx6sKPeJBd" true]
["INSERT INTO t (d, a, b, c) VALUES (?, ?, ?, ?)" nil "XswlIfaMosHdk-rbi48Hm5jMC ztjVar" "5Wmrld3k" "qnOCsL1W EKyQhvUQxs-fgzNu87d_PfdZ"]
["SELECT * FROM t WHERE ?" true]
["SELECT * FROM t"]
["INSERT INTO u (d) VALUES (?)" -19157]
["UPDATE t SET b = ?, a = ?, d = ?, c = ? WHERE (? = d)" "d_Vjulsc08yknWAUIVP_9t_j25CN4q" "vz_tqtjaU3We oVc-V1YOiY7" true "K-VJuU7r-b6drFPrbHVDG-VI7 nOPY" "Z7L6FynRJl_1z93FJ8"]
["SELECT * FROM u WHERE ((NOT ?) AND (d = d))" false]
["DELETE FROM u"]
["SELECT * FROM t WHERE d"]
["INSERT INTO t (b, d, c, a) VALUES (?, ?, ?, ?)" "jaAUrdnJ7VjFah" nil "7DbS" "LP0riuD"]
["DELETE FROM v WHERE ?" true]
["INSERT INTO u (d) VALUES (?)" 238683]
["INSERT INTO v (a, b, c, d) VALUES (?, ?, ?, ?)" nil -175 -489151 false]
["UPDATE u SET d = ?" 311065074]
["SELECT * FROM t WHERE d"]
["UPDATE v SET d = ?, a = ? WHERE ((d AND (? = ?) AND (? AND ? AND d AND a)) = b)" nil false -13588741 -5613 false true]
["UPDATE u SET d = ?" 203751]
["UPDATE v SET d = ?, c = ?, a = ?" true -16102 false]
["SELECT * FROM v WHERE ((a = ?) OR (c = c))" -1219069]
["INSERT INTO v (c, b, a, d) VALUES (?, ?, ?, ?)" -376 509107 false nil]
["INSERT INTO t (a, b, c, d) VALUES (?, ?, ?, ?)" "SMtE_99XMKoeQCTEOk_-fLiM5rZZ0Nv" "PvK083-z3AteoOmdv" "0YxAgZWpKD2evP" true]
["INSERT INTO t (b, a, c, d) VALUES (?, ?, ?, ?)" "0k2WH7oqrutUaSoCYMJVsKcATyW5iS" "4O_Gr" "mTA82IoQ" nil]
["SELECT * FROM u WHERE ?" true]
["SELECT * FROM t"]
["INSERT INTO u (d) VALUES (?)" -2]
["INSERT INTO t (a, c, b, d) VALUES (?, ?, ?, ?)" "LiTlvmVc0pC_HuALVTQDYx11n8" "-uIQpNEhiscUEifmQ" " vZeFRS4jIMnom" false]
["INSERT INTO t (d, a, b, c) VALUES (?, ?, ?, ?)" true "SlZSxafZ-YMx" "LzbDkV2x2G71hEY4PgRT4rQ" "HOQg7k_ xNXYx7Goqrk0tnP"]
["SELECT * FROM u"]
["INSERT INTO v (c, d, a, b) VALUES (?, ?, ?, ?)" 3 nil nil -1]
["UPDATE u SET d = ? WHERE (d = ?)" 230 -209]
["INSERT INTO v (b, a, d, c) VALUES (?, ?, ?, ?)" 47 nil nil -815]
["SELECT * FROM u WHERE (? = ?)" 0 -223281881]
["SELECT * FROM t WHERE ?" false]
["SELECT * FROM t WHERE (? AND (? AND d AND d AND ?) AND ((? = d) OR ? OR (? = d) OR (NOT d)))" false nil nil "dzPIhC4KIZyRMceVU6sevlyX8208J9OG" false false]
["UPDATE t SET d = ?, b = ? WHERE ?" nil "Ro yY01-ZDFj3wQIeTl" nil]
["SELECT * FROM t WHERE (d AND (a = b))"]
["SELECT * FROM v WHERE d"]
["UPDATE t SET d = ?, a = ? WHERE (((? = b) AND (d OR ? OR d) AND (? = d) AND (? = ?)) OR (NOT (b = ?)) OR (b = ?))" false "JM05tORqmGtfy" "aC -K7OU7FDyyzlahvOmvLJxyeK5" true nil "q4MjMdYoJ1aA" "op3FlNKUN1E925w6 8xgir" "q8SIRCwpSBoSuU5cD9h9jEKRmG1" true]
["UPDATE u SET d = ? WHERE (? = d)" 45219329 -3056978]

              ]
             (mapv sql (:statements case)))))))

